typedef struct Pattern {
  int inst;
  int amode;
} Pattern;

static Pattern itable[] = {
  {Tinv, Mnam}, {Tbrk, Mnam}, {Trti, Mnam}, {Tret, Mnam},
  {Tfor, Mimm}, {Tfnd, Mimm}, {Tclc, Mnam}, {Tnop, Mnam},
  {Tapp, Mnam}, {Tamm, Mnam}, {Tspp, Mnam}, {Tsmm, Mnam},
  {Txpp, Mnam}, {Txmm, Mnam}, {Typp, Mnam}, {Tymm, Mnam},
  {Tjfb, Mrel}, {Tjfc, Mrel}, {Tjfd, Mrel}, {Tjfn, Mrel},
  {Tjfr, Mrel}, {Tjfu, Mrel}, {Tjfv, Mrel}, {Tjfz, Mrel},
  {Tjtb, Mrel}, {Tjtc, Mrel}, {Tjtd, Mrel}, {Tjtn, Mrel},
  {Tjtr, Mrel}, {Tjtu, Mrel}, {Tjtv, Mrel}, {Tjtz, Mrel},
  {Tpha, Mnam}, {Tphf, Mnam}, {Tphx, Mnam}, {Tphy, Mnam},
  {Tpla, Mnam}, {Tplf, Mnam}, {Tplx, Mnam}, {Tply, Mnam},
  {Ttaf, Mnam}, {Ttas, Mnam}, {Ttax, Mnam}, {Ttay, Mnam},
  {Ttfa, Mnam}, {Ttsa, Mnam}, {Ttxa, Mnam}, {Ttya, Mnam},
  {Tlda, Mimm}, {Tlda, Mabs}, {Tlda, Mzpg}, {Tlda, Mvec},
  {Tlda, Mabx}, {Tlda, Maby}, {Tlda, Mzpx}, {Tlda, Mzpy},
  {Tzra, Mnam}, {Tsta, Mabs}, {Tsta, Mzpg}, {Tsta, Mvec},
  {Tsta, Mabx}, {Tsta, Maby}, {Tsta, Mzpx}, {Tsta, Mzpy},
  {Tzrx, Mnam}, {Tldx, Mimm}, {Tldx, Mabs}, {Tldx, Maby},
  {Tldx, Mzpg}, {Tldx, Mzpy}, {Tldx, Mvec}, {Tldx, Mzyv},
  {Tzry, Mnam}, {Tldy, Mimm}, {Tldy, Mabs}, {Tldy, Mabx},
  {Tldy, Mzpg}, {Tldy, Mzpx}, {Tldy, Mvec}, {Tldy, Mzvx},
  {Tcmp, Mimm}, {Tcmp, Mabs}, {Tcmp, Mzpg}, {Tcmp, Mvec},
  {Tcmp, Mabx}, {Tcmp, Maby}, {Tcmp, Mzpx}, {Tcmp, Mzpy},
  {Tjmp, Mrel}, {Tjmp, Mabs}, {Tjmp, Mzpg}, {Tjmp, Mvec},
  {Tjmp, Mabx}, {Tjmp, Maby}, {Tjmp, Mzpx}, {Tjmp, Mzpy},
  {Tstx, Mabs}, {Tstx, Maby}, {Tstx, Mzpg}, {Tstx, Mzpy},
  {Tstx, Mvec}, {Tstx, Mzyv}, {Tlda, Mzvx}, {Tlda, Mzyv},
  {Tsty, Mabs}, {Tsty, Mabx}, {Tsty, Mzpg}, {Tsty, Mzpx},
  {Tsty, Mvec}, {Tsty, Mzvx}, {Tsta, Mzvx}, {Tsta, Mzyv},
  {Tnta, Mnam}, {Tcal, Mabs}, {Tcal, Mzpg}, {Tcal, Mvec},
  {Tcal, Mabx}, {Tcal, Maby}, {Tcal, Mzpx}, {Tcal, Mzpy},
  {Tcal, Mzvx}, {Tcal, Mzyv}, {Tjmp, Mzvx}, {Tjmp, Mzyv},
  {Tcmp, Mzvx}, {Tcmp, Mzyv}, {Tsla, Mnam}, {Tsra, Mnam},
  {Tinc, Mabs}, {Tinc, Mabx}, {Tinc, Maby}, {Tinc, Mzpg},
  {Tinc, Mzpx}, {Tinc, Mzpy}, {Tinc, Mvec}, {Tinc, Mzvx},
  {Tinc, Mzyv}, {Tcpx, Mimm}, {Tcpx, Mabs}, {Tcpx, Maby},
  {Tcpx, Mzpg}, {Tcpx, Mzpy}, {Tcpx, Mvec}, {Tcpx, Mzyv},
  {Tdec, Mabs}, {Tdec, Mabx}, {Tdec, Maby}, {Tdec, Mzpg},
  {Tdec, Mzpx}, {Tdec, Mzpy}, {Tdec, Mvec}, {Tdec, Mzvx},
  {Tdec, Mzyv}, {Tcpy, Mimm}, {Tcpy, Mabs}, {Tcpy, Mabx},
  {Tcpy, Mzpg}, {Tcpy, Mzpx}, {Tcpy, Mvec}, {Tcpy, Mzvx},
  {Tbit, Mimm}, {Tbit, Mabs}, {Tbit, Mzpg}, {Tbit, Mvec},
  {Tbit, Mabx}, {Tbit, Maby}, {Tbit, Mzpx}, {Tbit, Mzpy},
  {Tand, Mimm}, {Tand, Mabs}, {Tand, Mzpg}, {Tand, Mvec},
  {Tand, Mabx}, {Tand, Maby}, {Tand, Mzpx}, {Tand, Mzpy},
  {Tbor, Mimm}, {Tbor, Mabs}, {Tbor, Mzpg}, {Tbor, Mvec},
  {Tbor, Mabx}, {Tbor, Maby}, {Tbor, Mzpx}, {Tbor, Mzpy},
  {Txor, Mimm}, {Txor, Mabs}, {Txor, Mzpg}, {Txor, Mvec},
  {Txor, Mabx}, {Txor, Maby}, {Txor, Mzpx}, {Txor, Mzpy},
  {Tadc, Mimm}, {Tadc, Mabs}, {Tadc, Mzpg}, {Tadc, Mvec},
  {Tadc, Mabx}, {Tadc, Maby}, {Tadc, Mzpx}, {Tadc, Mzpy},
  {Tsbc, Mimm}, {Tsbc, Mabs}, {Tsbc, Mzpg}, {Tsbc, Mvec},
  {Tsbc, Mabx}, {Tsbc, Maby}, {Tsbc, Mzpx}, {Tsbc, Mzpy},
  {Tadd, Mimm}, {Tadd, Mabs}, {Tadd, Mzpg}, {Tadd, Mvec},
  {Tadd, Mabx}, {Tadd, Maby}, {Tadd, Mzpx}, {Tadd, Mzpy},
  {Tsub, Mimm}, {Tsub, Mabs}, {Tsub, Mzpg}, {Tsub, Mvec},
  {Tsub, Mabx}, {Tsub, Maby}, {Tsub, Mzpx}, {Tsub, Mzpy},
  {Tbit, Mzvx}, {Tbit, Mzyv}, {Tand, Mzvx}, {Tand, Mzyv},
  {Tbor, Mzvx}, {Tbor, Mzyv}, {Txor, Mzvx}, {Txor, Mzyv},
  {Tadc, Mzvx}, {Tadc, Mzyv}, {Tsbc, Mzvx}, {Tsbc, Mzyv},
  {Tadd, Mzvx}, {Tadd, Mzyv}, {Tsub, Mzvx}, {Tsub, Mzyv},
  {Tnot, Mzpg}, {Tnot, Mzpx}, {Tnot, Mabs}, {Tnot, Mabx},
  {Tshl, Mzpg}, {Tshl, Mzpx}, {Tshl, Mabs}, {Tshl, Mabx},
  {Tshr, Mzpg}, {Tshr, Mzpx}, {Tshr, Mabs}, {Tshr, Mabx},
  {Tinv, Mnam}, {Tinv, Mnam}, {Tinv, Mnam}, {Tinv, Mnam}
};

